name: ai_vision_pro
description: "Advanced AI-powered visual recognition platform with enterprise features"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  
  # Camera & Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.3.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  
  # AI & ML
  # google_ml_kit: ^0.16.0  # Use stable version
  google_ml_kit: ^0.20.0
  tflite_flutter: ^0.10.4
  google_generative_ai: ^0.2.2
  
  # Advanced Features (REMOVED speech_to_text to fix build issues)
  flutter_tts: ^3.8.3     # Text-to-speech only
  translator: '^1.0.3+1'     # Fixed version
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  
  # Storage & Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.6
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.3
  connectivity_plus: ^6.1.4
  
  # State Management & Architecture
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Monetization
  in_app_purchase: ^3.1.11
  google_mobile_ads: ^6.0.0
  
  # Security & Authentication
  local_auth: ^2.1.7
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.20.2
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  
  # UI Enhancements
  lottie: ^2.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  badges: ^3.1.2
  confetti: ^0.7.0
  sensors_plus: ^6.1.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  font_awesome_flutter: ^10.8.0
  cloud_functions: ^5.6.2
  pdf: ^3.11.3
  csv: ^6.0.0
  open_file: ^3.5.10
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  audioplayers: ^6.5.1
  archive: ^3.6.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/sounds/
    - assets/icons/
    - assets/tutorials/
    
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash_logo.png"
  android_12:
    image: "assets/images/splash_logo.png"
    color: "#FFFFFF"